import type { TechnologyRecord } from '@/contracts/datasources/ExperienceContract'

const technologies: Record<string, TechnologyRecord> = {
    javascript: {
        id: '1',
        name: 'JavaScript',
        icon: 'https://raw.githubusercontent.com/devicons/devicon/master/icons/javascript/javascript-original.svg',
        webUrl: 'https://developer.mozilla.org/es/docs/Web/JavaScript',
        description: 'Javascript',
    },
    jquery: {
        id: '2',
        name: 'JQuery',
        icon: 'https://raw.githubusercontent.com/devicons/devicon/master/icons/jquery/jquery-original.svg',
        webUrl: 'https://jquery.com/',
        description: 'JQuery',
    },
    php: {
        id: '3',
        name: 'PHP',
        icon: 'https://raw.githubusercontent.com/devicons/devicon/master/icons/php/php-original.svg',
        webUrl: 'https://www.php.net/',
        description: 'PHP',
    },
    codeIgniter: {
        id: '4',
        name: 'CodeIgniter',
        icon: 'https://codeigniter.com/assets/icons/ci-logo.png',
        webUrl: 'https://codeigniter.com/',
        description: 'CodeIgniter',
    },
    wordpress: {
        id: '5',
        name: 'Wordpress',
        icon: 'https://raw.githubusercontent.com/devicons/devicon/master/icons/wordpress/wordpress-original.svg',
        webUrl: 'https://wordpress.org/',
        description: 'Wordpress',
    },
    laravel: {
        id: '6',
        name: 'Laravel',
        icon: 'https://raw.githubusercontent.com/laravel/art/d5f5e725c27f877ed032225fe0b00afee9337d0f/laravel-logo.svg',
        webUrl: 'https://laravel.com/',
        description: 'Laravel',
    },
    vue: {
        id: '7',
        name: 'Vue.js',
        icon: 'https://raw.githubusercontent.com/devicons/devicon/master/icons/vuejs/vuejs-original.svg',
        webUrl: 'https://vuejs.org/',
        description: 'Vue.js',
    },
    typescript: {
        id: '8',
        name: 'TypeScript',
        icon: 'https://raw.githubusercontent.com/devicons/devicon/master/icons/typescript/typescript-original.svg',
        webUrl: 'https://www.typescriptlang.org/',
        description: 'TypeScript',
    },
    postgreSQL: {
        id: '9',
        name: 'PostgreSQL',
        icon: 'https://raw.githubusercontent.com/devicons/devicon/master/icons/postgresql/postgresql-original.svg',
        webUrl: 'https://www.postgresql.org/',
        description: 'PostgreSQL',
    },
    mariaDB: {
        id: '10',
        name: 'MariaDB',
        icon: 'https://raw.githubusercontent.com/devicons/devicon/master/icons/mariadb/mariadb-original.svg',
        webUrl: 'https://mariadb.org/',
        description: 'MariaDB',
    },
    react: {
        id: '11',
        name: 'React',
        icon: 'https://raw.githubusercontent.com/devicons/devicon/master/icons/react/react-original.svg',
        webUrl: 'https://reactjs.org/',
        description: 'React',
    },
    reactNative: {
        id: '12',
        name: 'React Native',
        icon: 'https://raw.githubusercontent.com/devicons/devicon/master/icons/react/react-original.svg',
        webUrl: 'https://reactnative.dev/',
        description: 'React Native',
    },
    nodejs: {
        id: '13',
        name: 'Node.js',
        icon: 'https://raw.githubusercontent.com/devicons/devicon/master/icons/nodejs/nodejs-original.svg',
        webUrl: 'https://nodejs.org/',
        description: 'Node.js',
    },
    express: {
        id: '14',
        name: 'Express.js',
        icon: 'https://raw.githubusercontent.com/devicons/devicon/master/icons/express/express-original.svg',
        webUrl: 'https://expressjs.com/',
        description: 'Express.js',
    },
    sqlServer: {
        id: '15',
        name: 'SQL Server',
        icon: 'https://raw.githubusercontent.com/devicons/devicon/master/icons/microsoftsqlserver/microsoftsqlserver-plain.svg',
        webUrl: 'https://www.microsoft.com/en-us/sql-server/',
        description: 'SQL Server',
    },
    dart: {
        id: '16',
        name: 'Dart',
        icon: 'https://raw.githubusercontent.com/devicons/devicon/master/icons/dart/dart-original.svg',
        webUrl: 'https://dart.dev/',
        description: 'Dart',
    },
    flutter: {
        id: '17',
        name: 'Flutter',
        icon: 'https://raw.githubusercontent.com/devicons/devicon/master/icons/flutter/flutter-original.svg',
        webUrl: 'https://flutter.dev/',
        description: 'Flutter',
    },
    livewire: {
        id: '18',
        name: 'Livewire',
        icon: '/assets/technologies/livewire-logo.png',
        webUrl: 'https://laravel-livewire.com/',
        description: 'Livewire',
    },
    nextjs: {
        id: '19',
        name: 'Next.js',
        icon: 'https://raw.githubusercontent.com/devicons/devicon/master/icons/nextjs/nextjs-original.svg',
        webUrl: 'https://nextjs.org/',
        description: 'Next.js',
    },
    alpinejs: {
        id: '20',
        name: 'Alpine.js',
        icon: 'https://alpinejs.dev/alpine_long.svg',
        webUrl: 'https://alpinejs.dev/',
        description: 'Alpine.js',
    },
    medusaJS: {
        id: '21',
        name: 'MedusaJS',
        icon: 'https://avatars.githubusercontent.com/u/74172715?s=200&v=4',
        webUrl: 'https://medusajs.com/',
        description: 'MedusaJS',
    },
    hetzner: {
        id: '22',
        name: 'Hetzner',
        icon: 'https://www.hetzner.com/favicon.ico',
        webUrl: 'https://www.hetzner.com/',
        description: 'Hetzner',
    },
    aws: {
        id: '23',
        name: 'AWS',
        icon: 'https://raw.githubusercontent.com/devicons/devicon/master/icons/amazonwebservices/amazonwebservices-plain-wordmark.svg',
        webUrl: 'https://aws.amazon.com/',
        description: 'AWS',
    },
    nestjs: {
        id: '24',
        name: 'NestJS',
        icon: 'https://nestjs.com/logo-small-gradient.0ed287ce.svg',
        webUrl: 'https://nestjs.com/',
        description: 'NestJS',
    },
    filamentphp: {
        id: '25',
        name: 'FilamentPHP',
        icon: 'https://filamentphp.com/favicon/favicon.ico',
        webUrl: 'https://filamentphp.com/',
        description: 'FilamentPHP',
    },
    tailwindcss: {
        id: '26',
        name: 'TailwindCSS',
        icon: 'https://raw.githubusercontent.com/devicons/devicon/master/icons/tailwindcss/tailwindcss-original.svg',
        webUrl: 'https://tailwindcss.com/',
        description: 'TailwindCSS',
    },
    rigels: {
        id: '27',
        name: 'Rigels.io',
        icon: '/assets/companies-logos/rigels-logo.svg',
        webUrl: 'https://rigels.io/',
        description: 'Rigels.io - Hosting Platform',
    },
    odoo: {
        id: '28',
        name: 'Odoo',
        icon: 'https://raw.githubusercontent.com/devicons/devicon/master/icons/odoo/odoo-original.svg',
        webUrl: 'https://www.odoo.com/',
        description: 'Odoo',
    },
    sqlite: {
        id: '29',
        name: 'SQLite',
        icon: 'https://raw.githubusercontent.com/devicons/devicon/master/icons/sqlite/sqlite-original.svg',
        webUrl: 'https://www.sqlite.org/',
        description: 'SQLite',
    },
}

export default technologies
